### ISSUE TITLE
Remove inline use of `flume::` and import it at the top of the file instead.

### ISSUE THREAD

**Issue by togglebyte** [togglebyte/tinyroute#3]
Change all code referring to `flume::Sender` and `flume::Receiver` to import the `Sender` and
`Receiver` at the top of the file, so `flume::Sender` can be rewritten as `Sender`.

E.g: https://github.com/togglebyte/tinyroute/blob/main/src/agent.rs#L234 this should be changed
from `rx: flume::Receiver<AgentMsg<A>>,` to `rx: Receiver<AgentMsg<A>>,` and `use flume::Receiver`
should be added to the top of the file with all the other imports.

**Comment by akhil484** [comment]
Hey, I would love to work on this issue. Can you assign it to me?
