### ISSUE TITLE
Replace the standard library hashmap with a faster HashMap

### ISSUE THREAD

**Issue by togglebyte** [togglebyte/tinyroute#4]
Replace usages of `std::collections::HashMap` with FxHash: https://crates.io/crates/fxhash.

* Add https://crates.io/crates/fxhash as a dependency
* update https://github.com/togglebyte/tinyroute/blob/main/src/router.rs#L2

**Comment by hsteinmueller** [comment]
Hi @togglebyte, I'd like to work on this (as a rust newbie).
Love your streams btw 😄
