### ISSUE TITLE
Remove unused runtimes.

### ISSUE THREAD

**Issue by togglebyte** [togglebyte/tinyroute#5]
Smol and AsyncStd are no longer used and should be removed.
The code inside `src/runtime/tokio_runtime` can be collapsed into a single file: `src/runtime.rs`.

1. Remove all but the tokio runtime.
2. Move all the code in `tokio_runtime` to `src/runtime.rs` and remove `src/runtime/`

**Comment by KanikaRaheja** [comment]
I want to work on this issue @togglebyte. Please assign this issue to me.

**Comment by togglebyte** [comment]
I messed up the issue description.

The entire runtime module should be removed from the project (this means removing src/runtime.rs) and remove the `mod runtime;` from lib.rs: https://github.com/KanikaRaheja/tinyroute/blob/main/src/lib.rs#L4

So the only thing that is left to do for this issue is:
1. remove https://github.com/KanikaRaheja/tinyroute/tree/main/src/runtime.rs directory
2. remove this line https://github.com/KanikaRaheja/tinyroute/blob/main/src/lib.rs#L4

This should make the tests pass and I will accept the PR
